name: Deploy Spring Boot Application

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-ecommerce-jar
          path: target/deploy-ecommerce.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-ecommerce-jar

      - name: Deploy to server or platform
        run: |
          # Example: Upload to a server or deploy to a hosting service
          # Replace this with your deployment commands, such as scp or a CLI
          echo "Deploying demo-ecommerce.jar to the target environment"
